apiVersion: v1
kind: Pod
metadata:
  name: test-rpc-pod
  labels:
    app: test-app
spec:
  containers:
    - name: rust-grpc-server
      image: 192.168.49.1:5000/rust-grpc-server:latest
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 50051